version: "3.8"

services:
  api:
    build: .
    container_name: summarizer-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    container_name: summarizer-worker
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: celery -A app.workers.celery_worker worker --loglevel=info

  redis:
    image: redis:7-alpine
    container_name: summarizer-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
